## Rust-written `events.log` containers must be readable here.
##
## # Purpose
##
## Pin one interoperability rule: an `events.log` stream that carries the
## 8-byte CodeTracer stream header the SECONDARY (Rust) CTFS writer emits is
## read correctly by this repo's legacy `events.log` reader, and yields
## byte-identical events to the same recording written without that header.
##
## # The defect this guards
##
## `codetracer-trace-format`'s Rust writer prefixes `events.log` with
## `HEADERV1` — the 5-byte magic `C0 DE 72 AC E2`, a format-version byte and
## two reserved bytes (`codetracer_trace_format_cbor_zstd/src/lib.rs`).  Both
## Rust readers (`codetracer_trace_reader/src/ctfs_reader.rs` and
## `seekable_reader.rs`) REQUIRE that prefix and skip it before walking
## chunks.  This repo's `readEvents` did not skip it, and instead read the
## magic as a chunk header: the first four bytes little-endian give a
## `compressedSize` of `0xAC72DEC0` (~2.9 GB), so the walk aborted with
##
##     chunk compressed data extends beyond events.log
##
## `ct-print` reaches that reader for EVERY container carrying an
## `events.log` (`codetracer_ct_print.nim`: `hasEventsLog` forces
## `preferSplit = false`), so a valid Rust-written trace was simply
## unreadable by `ct-print`.
##
## # Why this is a hard failure, never a skip
##
## The fixture below is CONSTRUCTED, not discovered, so there is no
## prerequisite to be missing and therefore no honest reason to skip: the
## test builds both containers itself from this repo's own writer and
## container primitives.  A test that could not run would be a test that
## proves nothing about interoperability while reporting green, which is the
## failure mode this repo's neighbouring suites were just cured of.
##
## # Mocking policy justification (workspace AGENTS.md)
##
## **Nothing is mocked.**  The recording is produced by the REAL
## `codetracer_trace_writer`, the container is assembled with the REAL
## `codetracer_ctfs/container` primitives, and it is read back through the
## REAL `openTrace` / `readEvents` — the same entry points `ct-print` calls.
## The only synthesised byte sequence is the 8-byte header itself, and it is
## written out literally rather than imported so that this test still fails
## if the Rust constant and this repo's reader drift apart: a shared constant
## would move on both sides at once and pin nothing.
##
## A recorded Rust-written fixture file was considered and rejected: it would
## have to be regenerated by a cross-repo build to stay honest, and a stale
## committed blob that silently stops representing the Rust writer is the
## same class of lie this test exists to prevent.

import std/os
import results
import codetracer_trace_writer
import codetracer_trace_reader
import codetracer_trace_types
import codetracer_ctfs/container

const
  tmpDir = "/tmp/ctfs_rust_header_test"
  plainBundle = tmpDir / "plain.ct"
  headerBundle = tmpDir / "with_header.ct"

  ## The Rust writer's `HEADERV1`, spelled out here on purpose (see the
  ## mocking-policy note above).
  HeaderV1: array[8, byte] = [
    0xC0'u8, 0xDE, 0x72, 0xAC, 0xE2,  # "CodeTracer" magic
    0x01,                              # stream format version 1
    0x00, 0x00                         # reserved, must be zero
  ]

  ## Internal files a legacy `events.log` bundle from this repo's writer
  ## carries.  `meta.dat` and `events.log` are mandatory; the rest are copied
  ## when present so the reconstructed container is a faithful twin.
  mandatoryFiles = ["meta.dat", "events.log"]
  optionalFiles = ["meta.json", "paths.json", "paths.dat"]

# ---------------------------------------------------------------------------
# Fixture construction
# ---------------------------------------------------------------------------

proc buildPlainBundle(path: string) =
  ## A real recording written by this repo's writer: `events.log` with NO
  ## stream header, which is what the Nim writer emits.
  removeFile(path)
  var w = newTraceWriter(path, "demo", @["--x"], "/wd").get()
  doAssert w.writePath("/wd/main.py").isOk
  doAssert w.writeFunction(0, 1, "main").isOk
  doAssert w.writeStep(0, 1).isOk
  doAssert w.writeCall(0).isOk
  doAssert w.writeStep(0, 2).isOk
  doAssert w.writeValue(0,
    ValueRecord(kind: vrkInt, intVal: 42, intTypeId: TypeId(0))).isOk
  doAssert w.writeReturn().isOk
  doAssert w.writeMetaDat().isOk
  doAssert w.close().isOk

proc buildHeaderBundle(srcPath, outPath: string) =
  ## Rebuild `srcPath` as a container whose `events.log` carries the Rust
  ## writer's 8-byte stream header, every other stream copied verbatim.
  let src = readCtfsFromFile(srcPath).get()

  var c = createCtfs()
  for name in mandatoryFiles:
    let payload = readInternalFile(src, name).get()
    doAssert payload.len > 0, name & " is empty in the source bundle"
    var f = c.addFile(name).get()
    if name == "events.log":
      var prefixed = newSeq[byte](HeaderV1.len + payload.len)
      for i in 0 ..< HeaderV1.len:
        prefixed[i] = HeaderV1[i]
      for i in 0 ..< payload.len:
        prefixed[HeaderV1.len + i] = payload[i]
      doAssert c.writeToFile(f, prefixed).isOk
    else:
      doAssert c.writeToFile(f, payload).isOk

  for name in optionalFiles:
    if not hasInternalFile(src, name):
      continue
    let payload = readInternalFile(src, name).get()
    var f = c.addFile(name).get()
    doAssert c.writeToFile(f, payload).isOk

  doAssert writeCtfsToFile(c, outPath).isOk

# ---------------------------------------------------------------------------
# Reading
# ---------------------------------------------------------------------------

proc readAllEvents(path: string): seq[TraceLowLevelEvent] =
  let readerRes = openTrace(path)
  doAssert readerRes.isOk,
    "openTrace(" & path & ") failed: " & readerRes.unsafeError
  var reader = readerRes.get()
  let evRes = reader.readEvents()
  doAssert evRes.isOk,
    "readEvents(" & path & ") failed: " & evRes.unsafeError &
    "\n  A container written by the Rust CTFS writer is VALID; refusing to " &
    "read it is this repo's bug, not the container's."
  reader.events

# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------

proc testFixtureReallyCarriesTheHeader() =
  ## Guard the guard.  If the reconstruction lost the prefix, every assertion
  ## below would pass while testing nothing.
  let bytes = readCtfsFromFile(headerBundle).get()
  let events = readInternalFile(bytes, "events.log").get()
  doAssert events.len > HeaderV1.len, "reconstructed events.log is too short"
  for i in 0 ..< HeaderV1.len:
    doAssert events[i] == HeaderV1[i],
      "reconstructed events.log byte " & $i & " is " & $events[i] &
      ", expected " & $HeaderV1[i] & " — the fixture does not carry the " &
      "Rust stream header, so this suite would prove nothing"
  echo "PASS: fixture carries the Rust HEADERV1 prefix"

proc testPlainBundleStillReads() =
  ## The Nim writer emits no prefix; the conditional skip must not disturb it.
  let events = readAllEvents(plainBundle)
  doAssert events.len > 0, "the unprefixed bundle decoded to zero events"
  echo "PASS: unprefixed events.log still reads (", events.len, " events)"

proc testHeaderBundleReadsIdentically() =
  ## The whole point: a Rust-shaped `events.log` must decode, and must decode
  ## to the SAME events as its unprefixed twin.
  let plain = readAllEvents(plainBundle)
  let withHeader = readAllEvents(headerBundle)
  doAssert withHeader.len == plain.len,
    "prefixed bundle decoded " & $withHeader.len & " events, unprefixed " &
    $plain.len
  doAssert withHeader.len > 0, "both bundles decoded to zero events"
  for i in 0 ..< plain.len:
    doAssert withHeader[i] == plain[i],
      "event " & $i & " differs between the prefixed and unprefixed bundles"
  echo "PASS: prefixed events.log decodes identically (", plain.len, " events)"

proc testJsonOutputMatches() =
  ## `ct-print --json-events` on an events.log bundle is exactly
  ## `openTrace` + `readEvents` + this serialization, so pinning the JSON
  ## pins the user-visible behaviour without rebuilding the binary.
  var plainReader = openTrace(plainBundle).get()
  doAssert plainReader.readEvents().isOk
  var headerReader = openTrace(headerBundle).get()
  doAssert headerReader.readEvents().isOk
  let a = plainReader.toJsonEvents()
  let b = headerReader.toJsonEvents()
  doAssert a == b,
    "JSON event streams differ:\n  unprefixed: " & a & "\n  prefixed:   " & b
  doAssert a.len > 2, "JSON event stream is empty"
  echo "PASS: --json-events output is byte-identical across both layouts"

when isMainModule:
  createDir(tmpDir)
  buildPlainBundle(plainBundle)
  buildHeaderBundle(plainBundle, headerBundle)

  testFixtureReallyCarriesTheHeader()
  testPlainBundleStillReads()
  testHeaderBundleReadsIdentically()
  testJsonOutputMatches()

  echo "All Rust events.log header interop tests passed"
