## Tests for ct-print --full / --events output.
##
## Strategy:
##   1. Build a representative .ct fixture in-process (same content as
##      tests/generate_ct_print_fixture.nim, but inline so the test can
##      run hermetically without a separate binary).
##   2. Read the fixture back via the same NewTraceReader path that ct-print
##      uses, and call buildFullDocument(). This validates the conversion
##      logic without shelling out.
##   3. Walk the resulting JSON and assert: variable values are present,
##      decoded with the right structure (Int -> i, String -> text, etc.),
##      call args/return values are decoded, IO bytes appear as base64,
##      and the events list is in deterministic order.
##   4. Snapshot test: dump the JSON, compare against a committed golden
##      file under tests/goldens/. The golden can be regenerated by setting
##      CT_PRINT_WRITE_GOLDEN=1 in the environment.

import std/[os, strutils, json]
import results
import codetracer_trace_writer/multi_stream_writer
import codetracer_trace_writer/value_stream
import codetracer_trace_writer/io_event_stream
import codetracer_trace_writer/call_stream
import codetracer_trace_writer/cbor
import codetracer_trace_writer/new_trace_reader
import codetracer_trace_types

# Pull in the buildFullDocument and FullOpts symbols from ct-print.
include codetracer_ct_print_lib

# The `include codetracer_ct_print_lib` line above pulls a small library
# split out of codetracer_ct_print.nim so its helpers are reachable from
# tests without compiling the CLI's `main` proc.

proc encodeValue(v: ValueRecord): seq[byte] =
  var enc = CborEncoder.init()
  enc.encodeCborValueRecord(v)
  enc.getBytes()

proc toBytesAscii(s: string): seq[byte] =
  result = newSeq[byte](s.len)
  for i in 0 ..< s.len:
    result[i] = byte(s[i])

proc buildFixtureBytes(): seq[byte] =
  var wRes = initMultiStreamWriter("test.ct", "ct_print_demo", chunkSize = 16)
  doAssert wRes.isOk, "initMultiStreamWriter: " & wRes.error
  var w = wRes.get()
  w.metadata.args = @["--demo", "fixture"]
  w.metadata.workdir = "/workspace/demo"

  let p0 = w.registerPath("/workspace/demo/main.py").get()
  let p1 = w.registerPath("/workspace/demo/util.py").get()
  let fnMain = w.registerFunction("main").get()
  let fnCompute = w.registerFunction("compute").get()
  let vnX = w.registerVarname("x").get()
  let vnName = w.registerVarname("name").get()
  let vnFlag = w.registerVarname("flag").get()
  let vnPi = w.registerVarname("pi").get()
  let vnNothing = w.registerVarname("nothing").get()
  let vnNumbers = w.registerVarname("numbers").get()
  let vnPair = w.registerVarname("pair").get()
  let vnPoint = w.registerVarname("point").get()
  let vnShape = w.registerVarname("shape").get()
  let vnArg = w.registerVarname("n").get()
  let tInt = w.registerType("int").get()
  let tStr = w.registerType("str").get()
  let tBool = w.registerType("bool").get()
  let tFloat = w.registerType("float").get()
  let tNone = w.registerType("None").get()
  let tList = w.registerType("List[int]").get()
  let tTuple = w.registerType("Tuple[str,int]").get()
  let tStruct = w.registerType("Point").get()
  let tVariant = w.registerType("Shape").get()

  var step0Vals = @[
    VariableValue(varnameId: vnX, typeId: tInt, data: encodeValue(
      ValueRecord(kind: vrkInt, intVal: 42, intTypeId: TypeId(tInt))))
  ]
  doAssert w.registerStep(p0, 1'u64, step0Vals).isOk
  doAssert w.registerCall(fnMain, @[]).isOk

  var step1Vals = @[
    VariableValue(varnameId: vnName, typeId: tStr, data: encodeValue(
      ValueRecord(kind: vrkString, text: "hello", strTypeId: TypeId(tStr))))
  ]
  doAssert w.registerStep(p0, 2'u64, step1Vals).isOk

  var step2Vals = @[
    VariableValue(varnameId: vnFlag, typeId: tBool, data: encodeValue(
      ValueRecord(kind: vrkBool, boolVal: true, boolTypeId: TypeId(tBool)))),
    VariableValue(varnameId: vnPi, typeId: tFloat, data: encodeValue(
      ValueRecord(kind: vrkFloat, floatVal: 3.14, floatTypeId: TypeId(tFloat))))
  ]
  doAssert w.registerStep(p0, 3'u64, step2Vals).isOk

  let listVal = ValueRecord(
    kind: vrkSequence,
    seqElements: @[
      ValueRecord(kind: vrkInt, intVal: 1, intTypeId: TypeId(tInt)),
      ValueRecord(kind: vrkInt, intVal: 2, intTypeId: TypeId(tInt)),
      ValueRecord(kind: vrkInt, intVal: 3, intTypeId: TypeId(tInt)),
    ],
    isSlice: false,
    seqTypeId: TypeId(tList))
  var step3Vals = @[
    VariableValue(varnameId: vnNothing, typeId: tNone, data: encodeValue(
      ValueRecord(kind: vrkNone, noneTypeId: TypeId(tNone)))),
    VariableValue(varnameId: vnNumbers, typeId: tList, data: encodeValue(listVal))
  ]
  doAssert w.registerStep(p0, 4'u64, step3Vals).isOk

  let tupleVal = ValueRecord(
    kind: vrkTuple,
    tupleElements: @[
      ValueRecord(kind: vrkString, text: "answer", strTypeId: TypeId(tStr)),
      ValueRecord(kind: vrkInt, intVal: 42, intTypeId: TypeId(tInt)),
    ],
    tupleTypeId: TypeId(tTuple))
  var step4Vals = @[
    VariableValue(varnameId: vnPair, typeId: tTuple, data: encodeValue(tupleVal))
  ]
  doAssert w.registerStep(p0, 5'u64, step4Vals).isOk

  doAssert w.registerStep(p0, 6'u64, @[]).isOk
  doAssert w.registerIOEvent(ioStdout, "computing...\n".toBytesAscii).isOk
  let argN = ValueRecord(kind: vrkInt, intVal: 7, intTypeId: TypeId(tInt))
  let argEnc = encodeValue(argN)
  let callArgs = @[CallArg(varnameId: vnArg, value: argEnc)]
  doAssert w.registerCall(fnCompute, callArgs).isOk

  let structVal = ValueRecord(
    kind: vrkStruct,
    fieldValues: @[
      ValueRecord(kind: vrkInt, intVal: 1, intTypeId: TypeId(tInt)),
      ValueRecord(kind: vrkInt, intVal: 2, intTypeId: TypeId(tInt)),
    ],
    structTypeId: TypeId(tStruct))
  var step6Vals = @[
    VariableValue(varnameId: vnPoint, typeId: tStruct, data: encodeValue(structVal))
  ]
  doAssert w.registerStep(p1, 1'u64, step6Vals).isOk

  let variantVal = ValueRecord(
    kind: vrkVariant,
    discriminator: "Circle",
    contents: @[ValueRecord(
      kind: vrkStruct,
      fieldValues: @[
        ValueRecord(kind: vrkInt, intVal: 5, intTypeId: TypeId(tInt)),
      ],
      structTypeId: TypeId(tStruct))],
    variantTypeId: TypeId(tVariant))
  var step7Vals = @[
    VariableValue(varnameId: vnShape, typeId: tVariant, data: encodeValue(variantVal))
  ]
  doAssert w.registerStep(p1, 2'u64, step7Vals).isOk

  doAssert w.registerStep(p1, 3'u64, @[]).isOk
  doAssert w.registerIOEvent(ioStderr, "warning: nothing\n".toBytesAscii).isOk
  let computeRet = encodeValue(
    ValueRecord(kind: vrkInt, intVal: 49, intTypeId: TypeId(tInt)))
  doAssert w.registerReturn(computeRet).isOk

  doAssert w.registerStep(p0, 7'u64, @[]).isOk
  let mainRet = encodeValue(
    ValueRecord(kind: vrkInt, intVal: 0, intTypeId: TypeId(tInt)))
  doAssert w.registerReturn(mainRet).isOk

  doAssert w.close().isOk
  result = w.toBytes()
  w.closeCtfs()

# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------

proc findEvent(events: JsonNode, predicate: proc(j: JsonNode): bool {.closure.}): JsonNode =
  for ev in events.elems:
    if predicate(ev):
      return ev
  raise newException(AssertionDefect, "event not found")

proc countWhere(events: JsonNode,
    predicate: proc(j: JsonNode): bool {.closure.}): int =
  for ev in events.elems:
    if predicate(ev):
      result += 1

proc test_top_level_shape() =
  let bytes = buildFixtureBytes()
  let readerRes = openNewTraceFromBytes(bytes)
  doAssert readerRes.isOk, readerRes.error
  var reader = readerRes.get()
  let root = buildFullDocument(reader, FullOpts(stripPaths: false))

  doAssert root.hasKey("metadata"), "missing metadata"
  doAssert root.hasKey("paths"), "missing paths"
  doAssert root.hasKey("functions"), "missing functions"
  doAssert root.hasKey("varnames"), "missing varnames"
  doAssert root.hasKey("types"), "missing types"
  doAssert root.hasKey("counts"), "missing counts"
  doAssert root.hasKey("events"), "missing events"

  doAssert root["metadata"]["program"].getStr == "ct_print_demo"
  doAssert root["metadata"]["workdir"].getStr == "/workspace/demo"
  doAssert root["paths"].len == 2
  doAssert root["paths"][0].getStr == "/workspace/demo/main.py"
  doAssert root["paths"][1].getStr == "/workspace/demo/util.py"
  doAssert root["functions"][0].getStr == "main"
  doAssert root["functions"][1].getStr == "compute"
  doAssert root["counts"]["steps"].getInt == 10
  doAssert root["counts"]["calls"].getInt == 2
  doAssert root["counts"]["values"].getInt == 10
  doAssert root["counts"]["io_events"].getInt == 2
  echo "[ok] test_top_level_shape"

proc test_int_value_decoded() =
  let bytes = buildFixtureBytes()
  var reader = openNewTraceFromBytes(bytes).get()
  let root = buildFullDocument(reader, FullOpts(stripPaths: false))
  let events = root["events"]

  # Step 0 should have x = Int(42).
  let step0 = findEvent(events, proc(j: JsonNode): bool =
    j["kind"].getStr == "step" and j["step_index"].getInt == 0)
  doAssert step0["vars"].len == 1
  let xVar = step0["vars"][0]
  doAssert xVar["varname"].getStr == "x"
  doAssert xVar["value"]["kind"].getStr == "Int"
  doAssert xVar["value"]["i"].getInt == 42, "x should be 42"
  echo "[ok] test_int_value_decoded"

proc test_string_value_decoded() =
  let bytes = buildFixtureBytes()
  var reader = openNewTraceFromBytes(bytes).get()
  let root = buildFullDocument(reader, FullOpts(stripPaths: false))
  let events = root["events"]
  let step1 = findEvent(events, proc(j: JsonNode): bool =
    j["kind"].getStr == "step" and j["step_index"].getInt == 1)
  let nameVar = step1["vars"][0]
  doAssert nameVar["value"]["kind"].getStr == "String"
  doAssert nameVar["value"]["text"].getStr == "hello"
  echo "[ok] test_string_value_decoded"

proc test_bool_and_float_decoded() =
  let bytes = buildFixtureBytes()
  var reader = openNewTraceFromBytes(bytes).get()
  let root = buildFullDocument(reader, FullOpts(stripPaths: false))
  let events = root["events"]
  let step2 = findEvent(events, proc(j: JsonNode): bool =
    j["kind"].getStr == "step" and j["step_index"].getInt == 2)
  doAssert step2["vars"].len == 2
  let flagVar = step2["vars"][0]
  doAssert flagVar["value"]["kind"].getStr == "Bool"
  doAssert flagVar["value"]["b"].getBool == true
  let piVar = step2["vars"][1]
  doAssert piVar["value"]["kind"].getStr == "Float"
  doAssert abs(piVar["value"]["f"].getFloat - 3.14) < 1e-9
  echo "[ok] test_bool_and_float_decoded"

proc test_sequence_full_elements() =
  let bytes = buildFixtureBytes()
  var reader = openNewTraceFromBytes(bytes).get()
  let root = buildFullDocument(reader, FullOpts(stripPaths: false))
  let events = root["events"]
  let step3 = findEvent(events, proc(j: JsonNode): bool =
    j["kind"].getStr == "step" and j["step_index"].getInt == 3)
  # Step 3 has [nothing, numbers]. We want numbers (the second var).
  doAssert step3["vars"].len == 2
  let nothingVar = step3["vars"][0]
  doAssert nothingVar["value"]["kind"].getStr == "None"
  let numbersVar = step3["vars"][1]
  doAssert numbersVar["value"]["kind"].getStr == "Sequence"
  let elems = numbersVar["value"]["elements"]
  doAssert elems.len == 3
  doAssert elems[0]["kind"].getStr == "Int" and elems[0]["i"].getInt == 1
  doAssert elems[1]["kind"].getStr == "Int" and elems[1]["i"].getInt == 2
  doAssert elems[2]["kind"].getStr == "Int" and elems[2]["i"].getInt == 3
  doAssert numbersVar["value"]["is_slice"].getBool == false
  echo "[ok] test_sequence_full_elements"

proc test_tuple_decoded() =
  let bytes = buildFixtureBytes()
  var reader = openNewTraceFromBytes(bytes).get()
  let root = buildFullDocument(reader, FullOpts(stripPaths: false))
  let events = root["events"]
  let step4 = findEvent(events, proc(j: JsonNode): bool =
    j["kind"].getStr == "step" and j["step_index"].getInt == 4)
  let pairVar = step4["vars"][0]
  doAssert pairVar["value"]["kind"].getStr == "Tuple"
  let elems = pairVar["value"]["elements"]
  doAssert elems.len == 2
  doAssert elems[0]["kind"].getStr == "String" and elems[0]["text"].getStr == "answer"
  doAssert elems[1]["kind"].getStr == "Int" and elems[1]["i"].getInt == 42
  echo "[ok] test_tuple_decoded"

proc test_struct_decoded() =
  let bytes = buildFixtureBytes()
  var reader = openNewTraceFromBytes(bytes).get()
  let root = buildFullDocument(reader, FullOpts(stripPaths: false))
  let events = root["events"]
  let step6 = findEvent(events, proc(j: JsonNode): bool =
    j["kind"].getStr == "step" and j["step_index"].getInt == 6)
  let pointVar = step6["vars"][0]
  doAssert pointVar["value"]["kind"].getStr == "Struct"
  let fields = pointVar["value"]["field_values"]
  doAssert fields.len == 2
  doAssert fields[0]["i"].getInt == 1
  doAssert fields[1]["i"].getInt == 2
  echo "[ok] test_struct_decoded"

proc test_variant_decoded() =
  let bytes = buildFixtureBytes()
  var reader = openNewTraceFromBytes(bytes).get()
  let root = buildFullDocument(reader, FullOpts(stripPaths: false))
  let events = root["events"]
  let step7 = findEvent(events, proc(j: JsonNode): bool =
    j["kind"].getStr == "step" and j["step_index"].getInt == 7)
  let shapeVar = step7["vars"][0]
  doAssert shapeVar["value"]["kind"].getStr == "Variant"
  doAssert shapeVar["value"]["discriminator"].getStr == "Circle"
  let contents = shapeVar["value"]["contents"]
  doAssert contents["kind"].getStr == "Struct"
  doAssert contents["field_values"][0]["i"].getInt == 5
  echo "[ok] test_variant_decoded"

proc test_call_entry_args() =
  let bytes = buildFixtureBytes()
  var reader = openNewTraceFromBytes(bytes).get()
  let root = buildFullDocument(reader, FullOpts(stripPaths: false))
  let events = root["events"]
  # Find the call_entry for `compute`
  let callEv = findEvent(events, proc(j: JsonNode): bool =
    j["kind"].getStr == "call_entry" and j.hasKey("function") and
    j["function"].getStr == "compute")
  doAssert callEv["args"].len == 1
  let arg0 = callEv["args"][0]
  doAssert arg0["varname"].getStr == "n"
  doAssert arg0["value"]["kind"].getStr == "Int"
  doAssert arg0["value"]["i"].getInt == 7
  echo "[ok] test_call_entry_args"

proc test_call_exit_return_value() =
  let bytes = buildFixtureBytes()
  var reader = openNewTraceFromBytes(bytes).get()
  let root = buildFullDocument(reader, FullOpts(stripPaths: false))
  let events = root["events"]
  let computeExit = findEvent(events, proc(j: JsonNode): bool =
    j["kind"].getStr == "call_exit" and j.hasKey("function") and
    j["function"].getStr == "compute")
  doAssert computeExit["return_value"]["kind"].getStr == "Int"
  doAssert computeExit["return_value"]["i"].getInt == 49
  let mainExit = findEvent(events, proc(j: JsonNode): bool =
    j["kind"].getStr == "call_exit" and j.hasKey("function") and
    j["function"].getStr == "main")
  doAssert mainExit["return_value"]["kind"].getStr == "Int"
  doAssert mainExit["return_value"]["i"].getInt == 0
  echo "[ok] test_call_exit_return_value"

proc test_io_events_present() =
  let bytes = buildFixtureBytes()
  var reader = openNewTraceFromBytes(bytes).get()
  let root = buildFullDocument(reader, FullOpts(stripPaths: false))
  let events = root["events"]
  let stdoutEv = findEvent(events, proc(j: JsonNode): bool =
    j["kind"].getStr == "io" and j["io_kind"].getStr == "ioStdout")
  doAssert stdoutEv["text"].getStr == "computing...\n"
  doAssert stdoutEv["bytes_len"].getInt == 13
  let stderrEv = findEvent(events, proc(j: JsonNode): bool =
    j["kind"].getStr == "io" and j["io_kind"].getStr == "ioStderr")
  doAssert stderrEv["text"].getStr == "warning: nothing\n"
  echo "[ok] test_io_events_present"

proc test_event_counts() =
  let bytes = buildFixtureBytes()
  var reader = openNewTraceFromBytes(bytes).get()
  let root = buildFullDocument(reader, FullOpts(stripPaths: false))
  let events = root["events"]
  doAssert countWhere(events, proc(j: JsonNode): bool =
    j["kind"].getStr == "step") == 10, "10 step events"
  doAssert countWhere(events, proc(j: JsonNode): bool =
    j["kind"].getStr == "call_entry") == 2, "2 call_entry events"
  doAssert countWhere(events, proc(j: JsonNode): bool =
    j["kind"].getStr == "call_exit") == 2, "2 call_exit events"
  doAssert countWhere(events, proc(j: JsonNode): bool =
    j["kind"].getStr == "io") == 2, "2 IO events"
  echo "[ok] test_event_counts"

proc test_determinism() =
  ## Two independent invocations must produce byte-identical output.
  let bytes = buildFixtureBytes()
  var r1 = openNewTraceFromBytes(bytes).get()
  let s1 = pretty(buildFullDocument(r1, FullOpts(stripPaths: false)), indent = 2)
  var r2 = openNewTraceFromBytes(bytes).get()
  let s2 = pretty(buildFullDocument(r2, FullOpts(stripPaths: false)), indent = 2)
  doAssert s1 == s2, "ct-print --full output is not deterministic"
  echo "[ok] test_determinism"

proc test_strip_paths() =
  let bytes = buildFixtureBytes()
  var reader = openNewTraceFromBytes(bytes).get()
  let root = buildFullDocument(reader, FullOpts(stripPaths: true))
  doAssert root["metadata"]["workdir"].getStr == "<workdir>"
  doAssert root["paths"][0].getStr.startsWith("<workdir>/")
  doAssert root["paths"][0].getStr.endsWith("main.py")
  echo "[ok] test_strip_paths"

proc test_golden_snapshot() =
  ## Snapshot test — compare full output to a committed golden.
  ## Set CT_PRINT_WRITE_GOLDEN=1 to overwrite the golden.
  let goldenPath = currentSourcePath().parentDir() /
    "goldens" / "ct_print_full.json"
  let bytes = buildFixtureBytes()
  var reader = openNewTraceFromBytes(bytes).get()
  let actual = pretty(buildFullDocument(reader, FullOpts(stripPaths: true)),
    indent = 2)

  if getEnv("CT_PRINT_WRITE_GOLDEN", "") == "1":
    createDir(goldenPath.parentDir())
    writeFile(goldenPath, actual)
    echo "[wrote golden] " & goldenPath
    return

  if not fileExists(goldenPath):
    # First run: create the golden so subsequent runs can diff against it.
    createDir(goldenPath.parentDir())
    writeFile(goldenPath, actual)
    echo "[init golden] " & goldenPath
    return

  let expected = readFile(goldenPath)
  if actual != expected:
    let diffPath = goldenPath & ".actual"
    writeFile(diffPath, actual)
    raise newException(AssertionDefect,
      "ct-print --full output diverges from golden.\n" &
      "  expected: " & goldenPath & "\n" &
      "  actual:   " & diffPath & "\n" &
      "  To accept new output: CT_PRINT_WRITE_GOLDEN=1 nim c -r ...\n")
  echo "[ok] test_golden_snapshot"

proc test_trace_filter_provenance_materialized() =
  ## TF-M7: the trace-filter chain provenance recorded via
  ## `MultiStreamTraceWriter.setFilterProvenance` round-trips through
  ## `meta.dat` and is materialized into the JSON document at
  ## `metadata.trace_filter.filters[].{path,sha256}` per
  ## Trace-Filters.md § 7.  The sha256 is rendered as lowercase hex.
  var wRes = initMultiStreamWriter("test.ct", "tf_demo")
  doAssert wRes.isOk
  var w = wRes.get()
  w.metadata.workdir = "/w"
  var entries = newSeq[FilterProvenance](2)
  entries[0].path = "<inline:builtin-default>"
  for i in 0 ..< 32:
    entries[0].sha256[i] = byte(i)
  entries[1].path = "/etc/codetracer/override.toml"
  for i in 0 ..< 32:
    entries[1].sha256[i] = byte(255 - i)
  w.setFilterProvenance(entries)
  doAssert w.close().isOk
  let bytes = w.toBytes()
  w.closeCtfs()

  var reader = openNewTraceFromBytes(bytes).get()
  let root = buildFullDocument(reader, FullOpts(stripPaths: false))
  doAssert root["metadata"].hasKey("trace_filter"),
    "metadata.trace_filter must be present when provenance was recorded"
  let tf = root["metadata"]["trace_filter"]
  doAssert tf.hasKey("filters"), "trace_filter.filters missing"
  let filters = tf["filters"]
  doAssert filters.len == 2,
    "expected 2 filter entries, got " & $filters.len
  doAssert filters[0]["path"].getStr == "<inline:builtin-default>"
  doAssert filters[1]["path"].getStr == "/etc/codetracer/override.toml"

  # Sha256: lowercase hex, 64 chars, byte 0 of entry[0] is 0x00.
  let sha0 = filters[0]["sha256"].getStr
  doAssert sha0.len == 64, "sha256 hex length should be 64, got " & $sha0.len
  doAssert sha0[0..1] == "00"
  doAssert sha0[2..3] == "01"
  doAssert sha0 == sha0.toLowerAscii, "sha256 must be lowercase hex"

  let sha1 = filters[1]["sha256"].getStr
  doAssert sha1[0..1] == "ff"
  doAssert sha1[2..3] == "fe"

  echo "[ok] test_trace_filter_provenance_materialized"

proc test_trace_filter_provenance_absent_when_not_set() =
  ## TF-M7: when the writer does NOT call setFilterProvenance, the
  ## materialized JSON must NOT contain `metadata.trace_filter` (key
  ## absent, not present-with-empty-array).  This preserves the
  ## spec §7 distinction between "did not record" and "recorded
  ## empty".
  var wRes = initMultiStreamWriter("test.ct", "tf_demo")
  doAssert wRes.isOk
  var w = wRes.get()
  doAssert w.close().isOk
  let bytes = w.toBytes()
  w.closeCtfs()

  var reader = openNewTraceFromBytes(bytes).get()
  let root = buildFullDocument(reader, FullOpts(stripPaths: false))
  doAssert not root["metadata"].hasKey("trace_filter"),
    "metadata.trace_filter must be absent when provenance was not recorded"
  echo "[ok] test_trace_filter_provenance_absent_when_not_set"

# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------

test_top_level_shape()
test_int_value_decoded()
test_string_value_decoded()
test_bool_and_float_decoded()
test_sequence_full_elements()
test_tuple_decoded()
test_struct_decoded()
test_variant_decoded()
test_call_entry_args()
test_call_exit_return_value()
test_io_events_present()
test_event_counts()
test_determinism()
test_strip_paths()
test_trace_filter_provenance_materialized()
test_trace_filter_provenance_absent_when_not_set()
test_golden_snapshot()

echo ""
echo "All ct-print --full tests passed."
